{..............................................................................}
{ Summary PCB Layer Sets - Demo the use of a script to change PCB Layers       }
{ Copyright (c) 2003 by Altium Limited                                         }
{..............................................................................}

{..............................................................................}
Procedure TopLayers;
Begin
    ResetParameters;
    AddStringParameter ('TopSignal'         , 'True'  );
    AddStringParameter ('Mid1'              , 'False' );
    AddStringParameter ('Mid2'              , 'False' );
    AddStringParameter ('Mid3'              , 'False' );
    AddStringParameter ('Mid4'              , 'False' );
    AddStringParameter ('Mid5'              , 'False' );
    AddStringParameter ('Mid6'              , 'False' );
    AddStringParameter ('Mid7'              , 'False' );
    AddStringParameter ('Mid8'              , 'False' );
    AddStringParameter ('Mid9'              , 'False' );
    AddStringParameter ('Mid10'             , 'False' );
    AddStringParameter ('Mid11'             , 'False' );
    AddStringParameter ('Mid12'             , 'False' );
    AddStringParameter ('Mid13'             , 'False' );
    AddStringParameter ('Mid14'             , 'False' );
    AddStringParameter ('Mid15'             , 'False' );
    AddStringParameter ('Mid16'             , 'False' );
    AddStringParameter ('Mid17'             , 'False' );
    AddStringParameter ('Mid18'             , 'False' );
    AddStringParameter ('Mid19'             , 'False' );
    AddStringParameter ('Mid20'             , 'False' );
    AddStringParameter ('Mid21'             , 'False' );
    AddStringParameter ('Mid22'             , 'False' );
    AddStringParameter ('Mid23'             , 'False' );
    AddStringParameter ('Mid24'             , 'False' );
    AddStringParameter ('Mid25'             , 'False' );  
    AddStringParameter ('Mid26'             , 'False' );  
    AddStringParameter ('Mid27'             , 'False' );  
    AddStringParameter ('Mid28'             , 'False' );  
    AddStringParameter ('Mid29'             , 'False' );  
    AddStringParameter ('Mid30'             , 'False' );  
    AddStringParameter ('BottomSignal'      , 'False' );  
    AddStringParameter ('TopOverlay'        , 'True'  );  
    AddStringParameter ('BottomOverlay'     , 'False' );  
    AddStringParameter ('TopPaste'          , 'True'  );  
    AddStringParameter ('BottomPaste'       , 'False' );  
    AddStringParameter ('TopSolder'         , 'True'  );  
    AddStringParameter ('BottomSolder'      , 'False' );  
    AddStringParameter ('Plane1'            , 'False' );  
    AddStringParameter ('Plane2'            , 'False' );  
    AddStringParameter ('Plane3'            , 'False' );  
    AddStringParameter ('Plane4'            , 'False' );  
    AddStringParameter ('Plane5'            , 'False' );  
    AddStringParameter ('Plane6'            , 'False' );
    AddStringParameter ('Plane7'            , 'False' );  
    AddStringParameter ('Plane8'            , 'False' );  
    AddStringParameter ('Plane9'            , 'False' );  
    AddStringParameter ('Plane10'           , 'False' );  
    AddStringParameter ('Plane11'           , 'False' );  
    AddStringParameter ('Plane12'           , 'False' );  
    AddStringParameter ('Plane13'           , 'False' );  
    AddStringParameter ('Plane14'           , 'False' );  
    AddStringParameter ('Plane15'           , 'False' );  
    AddStringParameter ('Plane16'           , 'False' );  
    AddStringParameter ('DrillGuide'        , 'False' );  
    AddStringParameter ('KeepOut'           , 'False' );  
    AddStringParameter ('Mechanical1'       , 'False' );  
    AddStringParameter ('Mechanical2'       , 'False' );  
    AddStringParameter ('Mechanical3'       , 'False' );  
    AddStringParameter ('Mechanical4'       , 'False' );
    AddStringParameter ('Mechanical5'       , 'False' );
    AddStringParameter ('Mechanical6'       , 'False' );
    AddStringParameter ('Mechanical7'       , 'False' );
    AddStringParameter ('Mechanical8'       , 'False' );
    AddStringParameter ('Mechanical9'       , 'False' );
    AddStringParameter ('Mechanical10'      , 'False' );
    AddStringParameter ('Mechanical11'      , 'False' );  
    AddStringParameter ('Mechanical12'      , 'False' );  
    AddStringParameter ('Mechanical13'      , 'False' );  
    AddStringParameter ('Mechanical14'      , 'False' );
    AddStringParameter ('Mechanical15'      , 'False' );
    AddStringParameter ('Mechanical16'      , 'False' );
    AddStringParameter ('DrillDrawing'      , 'False' );  
    AddStringParameter ('MultiLayer'        , 'True'  );
    
    RunProcess ('Pcb:DocumentPreferences');

End;
{..............................................................................}

{..............................................................................}
Procedure BottomLayers;
Begin
  ResetParameters;
  AddStringParameter ('TopSignal'         , 'False' );
  AddStringParameter ('Mid1'              , 'False' ); 
  AddStringParameter ('Mid2'              , 'False' );
  AddStringParameter ('Mid3'              , 'False' );
  AddStringParameter ('Mid4'              , 'False' );  
  AddStringParameter ('Mid5'              , 'False' );  
  AddStringParameter ('Mid6'              , 'False' );
  AddStringParameter ('Mid7'              , 'False' );  
  AddStringParameter ('Mid8'              , 'False' );  
  AddStringParameter ('Mid9'              , 'False' );  
  AddStringParameter ('Mid10'             , 'False' );  
  AddStringParameter ('Mid11'             , 'False' );  
  AddStringParameter ('Mid12'             , 'False' );  
  AddStringParameter ('Mid13'             , 'False' );  
  AddStringParameter ('Mid14'             , 'False' );  
  AddStringParameter ('Mid15'             , 'False' );  
  AddStringParameter ('Mid16'             , 'False' );  
  AddStringParameter ('Mid17'             , 'False' );  
  AddStringParameter ('Mid18'             , 'False' );  
  AddStringParameter ('Mid19'             , 'False' );  
  AddStringParameter ('Mid20'             , 'False' );  
  AddStringParameter ('Mid21'             , 'False' );  
  AddStringParameter ('Mid22'             , 'False' );  
  AddStringParameter ('Mid23'             , 'False' );  
  AddStringParameter ('Mid24'             , 'False' );  
  AddStringParameter ('Mid25'             , 'False' );  
  AddStringParameter ('Mid26'             , 'False' );  
  AddStringParameter ('Mid27'             , 'False' );  
  AddStringParameter ('Mid28'             , 'False' );  
  AddStringParameter ('Mid29'             , 'False' );  
  AddStringParameter ('Mid30'             , 'False' );  
  AddStringParameter ('BottomSignal'      , 'True'  );  
  AddStringParameter ('TopOverlay'        , 'False' );  
  AddStringParameter ('BottomOverlay'     , 'True'  );  
  AddStringParameter ('TopPaste'          , 'False' );  
  AddStringParameter ('BottomPaste'       , 'True'  );  
  AddStringParameter ('TopSolder'         , 'False' );  
  AddStringParameter ('BottomSolder'      , 'True'  );  
  AddStringParameter ('Plane1'            , 'False' );  
  AddStringParameter ('Plane2'            , 'False' );  
  AddStringParameter ('Plane3'            , 'False' );  
  AddStringParameter ('Plane4'            , 'False' );  
  AddStringParameter ('Plane5'            , 'False' );  
  AddStringParameter ('Plane6'            , 'False' );  
  AddStringParameter ('Plane7'            , 'False' );  
  AddStringParameter ('Plane8'            , 'False' );  
  AddStringParameter ('Plane9'            , 'False' );  
  AddStringParameter ('Plane10'           , 'False' );  
  AddStringParameter ('Plane11'           , 'False' );  
  AddStringParameter ('Plane12'           , 'False' );  
  AddStringParameter ('Plane13'           , 'False' );  
  AddStringParameter ('Plane14'           , 'False' );  
  AddStringParameter ('Plane15'           , 'False' );  
  AddStringParameter ('Plane16'           , 'False' );
  AddStringParameter ('DrillGuide'        , 'False' );  
  AddStringParameter ('KeepOut'           , 'False' );  
  AddStringParameter ('Mechanical1'       , 'False' );  
  AddStringParameter ('Mechanical2'       , 'False' );  
  AddStringParameter ('Mechanical3'       , 'False' );  
  AddStringParameter ('Mechanical4'       , 'False' );  
  AddStringParameter ('Mechanical5'       , 'False' );
  AddStringParameter ('Mechanical6'       , 'False' );
  AddStringParameter ('Mechanical7'       , 'False' );
  AddStringParameter ('Mechanical8'       , 'False' );
  AddStringParameter ('Mechanical9'       , 'False' );
  AddStringParameter ('Mechanical10'      , 'False' );
  AddStringParameter ('Mechanical11'      , 'False' );  
  AddStringParameter ('Mechanical12'      , 'False' );  
  AddStringParameter ('Mechanical13'      , 'False' );  
  AddStringParameter ('Mechanical14'      , 'False' );
  AddStringParameter ('Mechanical15'      , 'False' );
  AddStringParameter ('Mechanical16'      , 'False' );
  AddStringParameter ('DrillDrawing'      , 'False' );  
  AddStringParameter ('MultiLayer'        , 'True'  );  
                                                     
  RunProcess ('Pcb:DocumentPreferences');
                                                     
End;
{..............................................................................}

{..............................................................................}
Procedure MechanicalLayers;
Begin
  ResetParameters;
  AddStringParameter ('TopSignal'         , 'False' );
  AddStringParameter ('Mid1'              , 'False' );  
  AddStringParameter ('Mid2'              , 'False' ); 
  AddStringParameter ('Mid3'              , 'False' ); 
  AddStringParameter ('Mid4'              , 'False' );   
  AddStringParameter ('Mid5'              , 'False' );   
  AddStringParameter ('Mid6'              , 'False' );   
  AddStringParameter ('Mid7'              , 'False' );   
  AddStringParameter ('Mid8'              , 'False' );   
  AddStringParameter ('Mid9'              , 'False' );   
  AddStringParameter ('Mid10'             , 'False' );   
  AddStringParameter ('Mid11'             , 'False' );   
  AddStringParameter ('Mid12'             , 'False' );   
  AddStringParameter ('Mid13'             , 'False' );   
  AddStringParameter ('Mid14'             , 'False' );   
  AddStringParameter ('Mid15'             , 'False' );   
  AddStringParameter ('Mid16'             , 'False' );
  AddStringParameter ('Mid17'             , 'False' );   
  AddStringParameter ('Mid18'             , 'False' );   
  AddStringParameter ('Mid19'             , 'False' );   
  AddStringParameter ('Mid20'             , 'False' );   
  AddStringParameter ('Mid21'             , 'False' );   
  AddStringParameter ('Mid22'             , 'False' );   
  AddStringParameter ('Mid23'             , 'False' );   
  AddStringParameter ('Mid24'             , 'False' );   
  AddStringParameter ('Mid25'             , 'False' );   
  AddStringParameter ('Mid26'             , 'False' );   
  AddStringParameter ('Mid27'             , 'False' );   
  AddStringParameter ('Mid28'             , 'False' );   
  AddStringParameter ('Mid29'             , 'False' );   
  AddStringParameter ('Mid30'             , 'False' );   
  AddStringParameter ('BottomSignal'      , 'False' );   
  AddStringParameter ('TopOverlay'        , 'False' );   
  AddStringParameter ('BottomOverlay'     , 'False' );   
  AddStringParameter ('TopPaste'          , 'False' );   
  AddStringParameter ('BottomPaste'       , 'False' );   
  AddStringParameter ('TopSolder'         , 'False' );   
  AddStringParameter ('BottomSolder'      , 'False' );   
  AddStringParameter ('Plane1'            , 'False' );   
  AddStringParameter ('Plane2'            , 'False' );   
  AddStringParameter ('Plane3'            , 'False' );   
  AddStringParameter ('Plane4'            , 'False' );   
  AddStringParameter ('Plane5'            , 'False' );   
  AddStringParameter ('Plane6'            , 'False' );   
  AddStringParameter ('Plane7'            , 'False' );   
  AddStringParameter ('Plane8'            , 'False' );   
  AddStringParameter ('Plane9'            , 'False' );   
  AddStringParameter ('Plane10'           , 'False' );   
  AddStringParameter ('Plane11'           , 'False' );   
  AddStringParameter ('Plane12'           , 'False' );   
  AddStringParameter ('Plane13'           , 'False' );   
  AddStringParameter ('Plane14'           , 'False' );   
  AddStringParameter ('Plane15'           , 'False' );   
  AddStringParameter ('Plane16'           , 'False' );   
  AddStringParameter ('DrillGuide'        , 'True'  );   
  AddStringParameter ('KeepOut'           , 'True'  );   
  AddStringParameter ('Mechanical1'       , 'True'  );   
  AddStringParameter ('Mechanical2'       , 'True'  );   
  AddStringParameter ('Mechanical3'       , 'True'  );   
  AddStringParameter ('Mechanical4'       , 'True'  );   
  AddStringParameter ('Mechanical5'       , 'True'  ); 
  AddStringParameter ('Mechanical6'       , 'True'  ); 
  AddStringParameter ('Mechanical7'       , 'True'  ); 
  AddStringParameter ('Mechanical8'       , 'True'  );
  AddStringParameter ('Mechanical9'       , 'True'  ); 
  AddStringParameter ('Mechanical10'      , 'True'  ); 
  AddStringParameter ('Mechanical11'      , 'True'  );   
  AddStringParameter ('Mechanical12'      , 'True'  );   
  AddStringParameter ('Mechanical13'      , 'True'  );   
  AddStringParameter ('Mechanical14'      , 'True'  ); 
  AddStringParameter ('Mechanical15'      , 'True'  ); 
  AddStringParameter ('Mechanical16'      , 'True'  ); 
  AddStringParameter ('DrillDrawing'      , 'True'  );   
  AddStringParameter ('MultiLayer'        , 'False' );   
  
  RunProcess ('Pcb:DocumentPreferences');
End;
{..............................................................................}

{..............................................................................}
Procedure AllLayers;
Begin
  ResetParameters;
  AddStringParameter ('TopSignal'         , 'True' );
  AddStringParameter ('Mid1'              , 'True' );  
  AddStringParameter ('Mid2'              , 'True' ); 
  AddStringParameter ('Mid3'              , 'True' ); 
  AddStringParameter ('Mid4'              , 'True' );   
  AddStringParameter ('Mid5'              , 'True' );   
  AddStringParameter ('Mid6'              , 'True' );   
  AddStringParameter ('Mid7'              , 'True' );   
  AddStringParameter ('Mid8'              , 'True' );   
  AddStringParameter ('Mid9'              , 'True' );   
  AddStringParameter ('Mid10'             , 'True' );   
  AddStringParameter ('Mid11'             , 'True' );   
  AddStringParameter ('Mid12'             , 'True' );   
  AddStringParameter ('Mid13'             , 'True' );   
  AddStringParameter ('Mid14'             , 'True' );   
  AddStringParameter ('Mid15'             , 'True' );   
  AddStringParameter ('Mid16'             , 'True' );   
  AddStringParameter ('Mid17'             , 'True' );   
  AddStringParameter ('Mid18'             , 'True' );   
  AddStringParameter ('Mid19'             , 'True' );   
  AddStringParameter ('Mid20'             , 'True' );   
  AddStringParameter ('Mid21'             , 'True' );   
  AddStringParameter ('Mid22'             , 'True' );   
  AddStringParameter ('Mid23'             , 'True' );   
  AddStringParameter ('Mid24'             , 'True' );   
  AddStringParameter ('Mid25'             , 'True' );   
  AddStringParameter ('Mid26'             , 'True' );   
  AddStringParameter ('Mid27'             , 'True' );
  AddStringParameter ('Mid28'             , 'True' );   
  AddStringParameter ('Mid29'             , 'True' );   
  AddStringParameter ('Mid30'             , 'True' );   
  AddStringParameter ('BottomSignal'      , 'True' );   
  AddStringParameter ('TopOverlay'        , 'True' );   
  AddStringParameter ('BottomOverlay'     , 'True' );   
  AddStringParameter ('TopPaste'          , 'True' );   
  AddStringParameter ('BottomPaste'       , 'True' );   
  AddStringParameter ('TopSolder'         , 'True' );   
  AddStringParameter ('BottomSolder'      , 'True' );   
  AddStringParameter ('Plane1'            , 'True' );   
  AddStringParameter ('Plane2'            , 'True' );   
  AddStringParameter ('Plane3'            , 'True' );   
  AddStringParameter ('Plane4'            , 'True' );   
  AddStringParameter ('Plane5'            , 'True' );   
  AddStringParameter ('Plane6'            , 'True' );   
  AddStringParameter ('Plane7'            , 'True' );   
  AddStringParameter ('Plane8'            , 'True' );   
  AddStringParameter ('Plane9'            , 'True' );   
  AddStringParameter ('Plane10'           , 'True' );   
  AddStringParameter ('Plane11'           , 'True' );   
  AddStringParameter ('Plane12'           , 'True' );   
  AddStringParameter ('Plane13'           , 'True' );   
  AddStringParameter ('Plane14'           , 'True' );   
  AddStringParameter ('Plane15'           , 'True' );   
  AddStringParameter ('Plane16'           , 'True' );   
  AddStringParameter ('DrillGuide'        , 'True'  );   
  AddStringParameter ('KeepOut'           , 'True'  );   
  AddStringParameter ('Mechanical1'       , 'True'  );   
  AddStringParameter ('Mechanical2'       , 'True'  );   
  AddStringParameter ('Mechanical3'       , 'True'  );   
  AddStringParameter ('Mechanical4'       , 'True'  );   
  AddStringParameter ('Mechanical5'       , 'True'  ); 
  AddStringParameter ('Mechanical6'       , 'True'  ); 
  AddStringParameter ('Mechanical7'       , 'True'  ); 
  AddStringParameter ('Mechanical8'       , 'True'  ); 
  AddStringParameter ('Mechanical9'       , 'True'  ); 
  AddStringParameter ('Mechanical10'      , 'True'  ); 
  AddStringParameter ('Mechanical11'      , 'True'  );   
  AddStringParameter ('Mechanical12'      , 'True'  );   
  AddStringParameter ('Mechanical13'      , 'True'  );   
  AddStringParameter ('Mechanical14'      , 'True'  ); 
  AddStringParameter ('Mechanical15'      , 'True'  ); 
  AddStringParameter ('Mechanical16'      , 'True'  ); 
  AddStringParameter ('DrillDrawing'      , 'True'  );   
  AddStringParameter ('MultiLayer'        , 'True' );   

  RunProcess ('Pcb:DocumentPreferences');
End;
{..............................................................................}

{..............................................................................}
