/*****************************************************************************
|*
|*  Copyright:      Copyright (c) 2008, Altium
|*
|*  Description:    Canopen server program. The OD entries from this server can
|*                  be queried by a remote client program.
|*
\*****************************************************************************/
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "framework.h"
#include "canopen.h"
/* main() *********************************************************************
 * This CANopen device uses CANopen features that are default generated by
 * the CANopen configurator (CO_OD.c/h and USER.c).  Except for USER.c, normally
 * you do not need to edit those files. Most important CANopen feature in this
 * example is SDO Server functionality.
 */
void main (int argc, char *argv[])
{
    int kp = 0;
    CO_ResetComm();   // Reset communication
    while (1)
    {
        CO_ProcessMain();
        User_ProcessMain();
    }
}
