/*****************************************************************
**
** File         : tcpipset.h
** Function     : settings for TCPIP stack
**
** Generated at : 2004/07/01 10:36:40
** Generated by : stackconfmake v1.1
**
** MANUAL CHANGES WILL BE OVERWRITTEN IF THIS FILE IS RE-GENERATED
**
******************************************************************/

#ifndef __TCPIPSET_H__
#define __TCPIPSET_H__

// optional features
#define OPTION_ETHERNET
// #define OPTION_SERIAL
// #define OPTION_UDP
#ifdef OPTION_UDP
// #define OPTION_DNS_SERVER
// #define OPTION_DNS_CLIENT
#endif
#define OPTION_ICMP_ECHO
// #define OPTION_HTTP_SERVER
// #define OPTION_FTP_SERVER
// #define OPTION_TELNET_SERVER
// #define OPTION_SMTP_CLIENT
// #define OPTION_FS

// TCP settings
#define TCP_SESSIONS 8
#define TCP_PORT_CLIENT_START 1000
#define TCP_PORT_CLIENT_END 2000
#define TCP_WATCHDOG_TICKS 300
#define TCP_RETRY_TICKS 10
#define TCP_RETRY_MAX 3

// Ethernet transport settings
#ifdef OPTION_ETHERNET
#define ARP_CACHE_ENTRIES 8
#ifdef OPTION_UDP
#define OPTION_DHCP
#endif
#endif

// DHCP settings
#ifdef OPTION_DHCP
#define DHCP_WAITOFFER 10
#define DHCP_WAITACK 10
#define DHCP_RENEWSLACK 10
#define DHCP_LEASETIME 600
#endif

// Serial transport settings
#ifdef OPTION_SERIAL
#define SERIAL_MODEM
#define SERIAL_PPP
// #define SERIAL_SLIP
#define SERIAL_CALLIN
// #define SERIAL_CALLOUT
#define SERIAL_BUFLEN 1500
#define SERIAL_PACKETTIME_TICKS 5
#define SERIAL_MODEMCONNECTTIME_TICKS 45
#define SERIAL_PPPCONNECTTIME_TICKS 15
#define SERIAL_MODEMBREAKTIME_TICKS 15
#endif

// HTTP-server settings
#ifdef OPTION_HTTP_SERVER
#define HTTP_DEF "httpdef.h"
#define HTTP_DIRINDEX "index.html"
#ifdef OPTION_FS
//#define HTTP_FS_ROOT ""
#endif
#endif

// FTP-server settings
#ifdef OPTION_FTP_SERVER
#define FTP_SESSIONS 2
#define FTP_SUBDIR_MAXDEPTH 5
#define FTP_VERBOSE
#endif

// TELNET-server settings
#ifdef OPTION_TELNET_SERVER
#define TELNET_SESSIONS 2
#endif

// FS settings
#ifdef OPTION_FS
#include "fsdef.h"
#endif

// hardware specific header
#include "tcpipsysset.h"

// global system header
#include "common/sys.h"

#endif

